### ISSUE TITLE
Investigate & implement Vimeo SDK

### ISSUE THREAD

**Issue by safaal28** [Quran-Journey/frontend#28]
- [ ] research different methods on implementing vimeo videos on web apps, and choose an ideal one for this project (most likely Vimeo SDK)
- [ ] implement basics of Vimeo SDK
- [ ] customize button layout to that of wireframe 
- [ ] look into incorporating feature for miniplayer that shows only audio without video when scrolling away down

**Comment by safaal28** [comment]
Estimated completion for first two points is Wednesday, third point is Friday

**Comment by SarahEddeb** [comment]
Covered in another issue
